


public class Snowflakes
{
	public String[] flipByDig(String[] s)
	{
		int N = s.length;
		String[] ret = new String[N];
		for (int i = 0; i < N; ++i) 
		{
			ret[i] = "";
			for (int j = 0; j < N; ++j) 
				ret[i] = ret[i] + s[Math.max(i, j)].charAt(Math.min(i,  j));
		}
		return ret;
	}
	
	public String[] flipByV(String[] s)
	{
		int N = s.length;
		String[] ret = new String[N];
		for (int i = 0; i < N; ++i)
		{
			ret[i] = "";
			for (int j = 0; j < N * 2; ++j)
			{
				if (j < N) ret[i] = ret[i] + s[i].charAt(N - 1 - j);
				else ret[i] = ret[i] + s[i].charAt(j - N);
			}
		}
		return ret;
	}
	
	public String[] flipByH(String[] s)
	{
		int N = s.length;
		String[] ret = new String[N * 2];
		for (int i = 0; i < N * 2; ++i)
		{
			ret[i] = "";
			for (int j = 0; j < N * 2; ++j) 
			{
				if (i < N) ret[i] = ret[i] + s[N - 1 - i].charAt(j);
				else ret[i] = ret[i] + s[i - N].charAt(j);
			}
		}
		return ret;
	}
	
	public String[] flareOut(String[] snowflake)
	{
		String[] ans = flipByH(flipByV(flipByDig(snowflake)));
		return ans;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, String[] p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		Snowflakes obj;
		String[] answer;
		obj = new Snowflakes();
		long startTime = System.currentTimeMillis();
		answer = obj.flareOut(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p1.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print("\"" + p1[i] + "\"");
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + answer[i] + "\"");
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p1.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (!answer[i].equals(p1[i])) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String[] p1;
		
		// ----- test 0 -----
		p0 = new String[]{".","..","*.*"};
		p1 = new String[]{"*.**.*","......","*....*","*....*","......","*.**.*"};
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"*","..",".*.",".**.",".*.**"};
		p1 = new String[]{"**.*..*.**","*.**..**.*",".*.*..*.*.","***....***","....**....","....**....","***....***",".*.*..*.*.","*.**..**.*","**.*..*.**"};
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{".","..","***"};
		p1 = new String[]{"******","*....*","*....*","*....*","*....*","******"};
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"*",".*","***"};
		p1 = new String[]{"******","**..**","*.**.*","*.**.*","**..**","******"};
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{".","..","***","...."};
		p1 = new String[]{"........",".******.",".*....*.",".*....*.",".*....*.",".*....*.",".******.","........"};
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
